# Generated by Django 2.0.2 on 2018-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180223_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='body_text',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
