# Generated by Django 2.0.2 on 2018-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180406_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
