# Generated by Django 2.0.2 on 2018-04-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180424_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.DateTimeField(null=True, verbose_name='event start'),
        ),
    ]
