# Generated by Django 2.0.2 on 2018-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20180424_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body_text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
