# Generated by Django 2.0.2 on 2018-04-24 17:03

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20180424_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body_text',
            field=markdownx.models.MarkdownxField(default='', max_length=2000),
        ),
    ]
