# Generated by Django 2.0.2 on 2018-04-25 15:51

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180425_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_logo',
            field=models.ImageField(blank=True, default='default/blank-profile.png', null=True, upload_to=events.models.logo_directory_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
