# Generated by Django 2.0.2 on 2018-04-26 21:18

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20180425_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail_long',
            field=markdownx.models.MarkdownxField(default='', max_length=2000, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail_small',
            field=models.TextField(default='', max_length=200, verbose_name='Description'),
        ),
    ]
