# Generated by Django 2.0.2 on 2018-04-27 17:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('events', '0025_auto_20180427_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resources',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Resources'),
        ),
    ]
