# Generated by Django 2.0.2 on 2018-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_project_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(null=True, verbose_name='URL to Github Repo'),
        ),
    ]
