# Generated by Django 2.0.2 on 2018-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20180427_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
