# Generated by Django 2.0.2 on 2018-04-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20180427_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='URL to Github Repo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
