# Generated by Django 2.0.2 on 2018-04-27 19:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20180427_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Resources'),
        ),
    ]
