# Generated by Django 2.0.2 on 2018-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20180427_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canjoin',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.NullBooleanField(),
        ),
    ]
