# Generated by Django 2.0.2 on 2018-05-16 13:07

from django.conf import settings
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20180507_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=markdownx.models.MarkdownxField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_text',
            field=markdownx.models.MarkdownxField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
