# Generated by Django 2.0.2 on 2018-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20180531_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsponsorship',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventsponsorship',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
