# Generated by Django 2.0.2 on 2018-07-31 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0036_auto_20180531_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', markdownx.models.MarkdownxField(default='', max_length=500, verbose_name='Description')),
                ('main_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('votes', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', markdownx.models.MarkdownxField(default='', max_length=500, verbose_name='Comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to=settings.AUTH_USER_MODEL)),
                ('parentIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Idea')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='comments',
            field=models.ManyToManyField(blank=True, to='events.IdeaComment'),
        ),
        migrations.AddField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='ideaTags'),
        ),
        migrations.AddField(
            model_name='idea',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
