# Generated by Django 2.0.2 on 2018-08-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_event_need_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='votes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
