# Generated by Django 2.0.2 on 2018-10-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_ideacomment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(default='', max_length=2000, verbose_name='API response')),
                ('github', models.URLField(blank=True, null=True, verbose_name='URL to Github Repo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
