# Generated by Django 2.0.2 on 2018-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_githubcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubcache',
            name='content',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='API response'),
        ),
    ]
