# Generated by Django 2.0.2 on 2018-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20181013_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubcache',
            name='content',
            field=models.TextField(blank=True, default='', max_length=100000, verbose_name='API response'),
        ),
    ]
