# Generated by Django 2.0.2 on 2019-01-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190111_1328'),
        ('events', '0047_event_carge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment'),
        ),
    ]
