# Generated by Django 2.0.2 on 2019-01-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_eventregistration_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='carge_amount',
            new_name='charge_amount',
        ),
    ]
