# Generated by Django 2.0.2 on 2019-01-15 00:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20190114_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=markdownx.models.MarkdownxField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
