# Generated by Django 2.0.2 on 2019-01-15 18:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=markdownx.models.MarkdownxField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
