# Generated by Django 2.0.2 on 2020-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_event_price_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='diet_restriction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='options_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='shirt_size',
            field=models.CharField(choices=[('WS', "Women's S"), ('WM', "Women's M"), ('WL', "Women's L"), ('WXL', "Women's XL"), ('MS', 'Men S'), ('MM', 'Men M'), ('ML', 'Men L'), ('MXL', 'Men XL')], default='', max_length=3),
        ),
    ]
