# Generated by Django 2.0.2 on 2020-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_auto_20200122_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_registration_options',
            field=models.BooleanField(default=False),
        ),
    ]
