# Generated by Django 2.0.2 on 2020-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_event_has_registration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_registration_options',
            field=models.NullBooleanField(),
        ),
    ]
