# Generated by Django 2.0.2 on 2020-01-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20200122_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='shirt_size',
            field=models.CharField(choices=[('WS', "Women's S"), ('WM', "Women's M"), ('WL', "Women's L"), ('WXL', "Women's XL"), ('MS', "Men's S"), ('MM', "Men's M"), ('ML', "Men's L"), ('MXL', "Men's XL")], default='', max_length=3),
        ),
    ]
