# Generated by Django 2.0.2 on 2020-01-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_auto_20200122_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='diet_restriction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
