# Generated by Django 2.0.2 on 2018-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uprofile',
            name='github_uname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
