# Generated by Django 2.0.2 on 2018-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0002_uprofile_github_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='uprofile',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
