# Generated by Django 2.0.2 on 2018-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0003_uprofile_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uprofile',
            options={'verbose_name': 'Extender User Profile', 'verbose_name_plural': 'Extender User Profiles'},
        ),
    ]
