# Generated by Django 2.0.2 on 2018-04-10 13:15

from django.db import migrations, models
import uprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0005_uprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/blank-profile.png', null=True, upload_to=uprofile.models.user_directory_path),
        ),
    ]
